version: '2.27.1'

services:

  mariadb:
    image: mariadb:11.3
    volumes:
      - flaggy_mariadb_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: flaggy
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"

volumes:
  flaggy_mariadb_data:
